version: '3.8'

services:
  # 1. قاعدة البيانات (PostgreSQL)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devopsdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. الـ Backend
  backend:
      build: ./backend
      environment:
        # بنجبر الـ API يشتغل على بورت 8080 جوه الدوكر
        - ASPNETCORE_HTTP_PORTS=8080 
      ports:
        - "8081:8080"  # <--- التغيير هنا (البورت الخارجي بقى 8081)
      depends_on:
        - db

  # 3. الـ Frontend
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  # عشان البيانات متتمسحش لو قفلنا الدوكر
  pgdata: